### ISSUE TITLE
Failed to run on windows

### ISSUE THREAD

**Issue by wsdjeg** [racer-rust/vim-racer#148]
@Shougo I just install this project in windows os, but I get following errors, I think maybe it is due to the encoding of output:

```
[deoplete] stderr from child process:b"thread '"
[deoplete] stderr from child process:b'searcher'
[deoplete] stderr from child process:b"' panicked at '"
[deoplete] stderr from child process:b'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }'
[deoplete] stderr from child process:b"', "
[deoplete] stderr from child process:b'C:\\Users\\wsdjeg\\.cargo\\registry\\src\\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\\racer-2.1.31\\src/bin/main.rs'
[deoplete] stderr from child process:b':'
[deoplete] stderr from child process:b'139'
[deoplete] stderr from child process:b':'
[deoplete] stderr from child process:b'24'
[deoplete] stderr from child process:b'\n'
[deoplete] stderr from child process:b'note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n'
[deoplete] stderr from child process:b'ERROR 2020-03-05T14:14:01.940143000Z: racer: Search thread panicked: Any\n'
[deoplete] stderr from child process:b"thread '"
[deoplete] stderr from child process:b'searcher\' panicked at \'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }\', C:\\Users\\wsdjeg\\.cargo\\registry\\src\\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\\racer-2.1.31\\src/bin/main.rs:139:24\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n'
[deoplete] stderr from child process:b'ERROR 2020-03-05T14:14:23.465374200Z: racer: Search thread panicked: Any\n'
[deoplete] stderr from child process:b"thread '"
[deoplete] stderr from child process:b'searcher\' panicked at \'called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }\', C:\\Users\\wsdjeg\\.cargo\\registry\\src\\mirrors.ustc.edu.cn-61ef6e0cd06fb9b8\\racer-2.1.31\\src/bin/main.rs:139:24\nnote: run with `RUST_BACKTRACE=1` environment variable to display a backtrace\n'
[deoplete] stderr from child process:b'ERROR 2020-03-05T14:14:30.506776900Z: racer: Search thread panicked: Any\n'
```

**Comment by wsdjeg** [comment]
Thanks for your work.
